apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 0
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: app
        image: demo-cluster-registry:5000/demo_app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
